### PR TITLE
Add file permission attribute to /var/log/chef

### PR DESCRIPTION
**Pull request by jsmickey**
I have a use case where my team needs to change the permissions of /var/log/chef/ for a third party log agent.  I added an attribute for the file permissions and set the default to 750.  This change will allow for changing the permissions by overriding the attribute.

### CODE REVIEW

**Comment by jtimberman** [comment]
I'm :thumbsdown:for adding more attributes to this cookbook.

**Comment by jsmickey** [comment]
Any recommendations how I solve my problem?  I would prefer not to manage a custom cookbook.

**Comment by ikurochkin** [comment]
@jsmickey You can use [chef-rewind](https://github.com/thommay/chef-rewind) to modify some properties of a resource.

**Comment by juliandunn** [comment]
You don't even need rewind for that... you can reopen a resource like this

resources('directory[/var/log/chef]').mode('0700')

in a wrapper cookbook.

**Comment by smorgrav** [comment]
I think this is a good idea - or change the default behavior?

Logs are generally there for other than root to see.

**Comment by jtimberman** [comment]
Coming back to this after vacation and ChefConf.

Personally, I'd rather we just make the directory mode `0755`.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by jsmickey** [comment]
I'm fine with removing the attribute and setting the permission to 755

Updated the pull request

**Pull request merged**
