### PR TITLE
Fix log_location regex possibility bug.

### PR DESCRIPTION
**Pull request by a1ph4g33k**
log_location must be wrapped in quotes or *nix values will be seen as regexs and completely break chef-client.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @a1ph4g33k

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by a1ph4g33k** [comment]
ping ?

**Comment by juliandunn** [comment]
Can you give an example of the undesired behavior?

**Comment by a1ph4g33k** [comment]
I set my log location value to /var/log/chef-client.log via my "core" role.

```ruby
default_attributes(
  {
    'chef_client' => {
      'interval' => 60,
      'config' => {
        'log_location' => "/var/log/chef/client.log"
      }
    }
  }
)
```

**Comment by a1ph4g33k** [comment]
There needs to be something else to delineate between things like the STDOUT/STDERR behavior and providing a real filepath. Maybe add an additional parameter "log_type" with 'named', 'class', or 'path' as option ?

**Comment by a1ph4g33k** [comment]
@juliandunn: Does this work better for you ? I appreciate your feedback.

**Comment by juliandunn** [comment]
That works. Thanks!

**Pull request merged**
